WEB/Controllers/AutorController.cs
using BIBLIOTECA_VIRTUAL.Models;
using BIBLIOTECA_VIRTUAL.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace BIBLIOTECA_VIRTUAL.Controllers
{
    public class AutorController : Controller
    {
        private readonly IAutor _iautor;

        public AutorController(IAutor autor)
        {
            _iautor = autor;
        }
        public IActionResult ListadoAutor()
        {
            return View(_iautor.GetAllAutores());
        }

        public IActionResult FormularioAutor()
        {
            return View();
        }

        public IActionResult AñadirAutor(Autor objAutor)
        {
            _iautor.AñadirAutor(objAutor);
            TempData["Mensaje"] = "Se añadio correctamente el autor!!!";
            return RedirectToAction("FormularioAutor");
        }

        public IActionResult FormularioEditAutor()
        {
            return View(_iautor.GetAllAutoresTrue());
        }

        [Route("Autor/FormularioModificar/{IdAutor}")]
        public IActionResult FormularioModificar(int IdAutor)
        {
            var objAutor = _iautor.GetIdAutorModificar(IdAutor);

            return View(objAutor);
        }

        public IActionResult ModificarAutor(Autor objAutor)
        {
            _iautor.EditDetails_Autor(objAutor);
            TempData["Mensaje"] = "Se modifico correctamente!!";
            return RedirectToAction("FormularioEditAutor");
        }

        [Route("Autor/EliminarAutor/{IdAutor}")]
        public IActionResult EliminarAutor(int IdAutor)
        {
            bool flag = _iautor.EliminarAutor(IdAutor);
            if (flag == true)
            {
                TempData["Mensaje"] = "Se elimino correctamente!!";
                return RedirectToAction("FormularioEditAutor");
            }
            else
            {
                TempData["Mensaje"] = "Hubo un error al momento de elimnar";
                return RedirectToAction("FormularioEditAutor");
            }
        }
    }
}

WEB/Controllers/VistaMainController.cs
using BIBLIOTECA_VIRTUAL.Models;
using BIBLIOTECA_VIRTUAL.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace BIBLIOTECA_VIRTUAL.Controllers
{
    public class VistaMainController : Controller
    {
        private readonly ILibro _ilibro;
        private readonly IAutor _iautor;
        private readonly IEditorial _ieditorial;
        private readonly IConsolidadoLibro _iconsolidado;
        public VistaMainController(ILibro libro, IAutor autor, IEditorial editorial, IConsolidadoLibro consolidadoLibro)
        {
            _ilibro = libro;
            _iautor = autor;
            _ieditorial = editorial;
            _iconsolidado = consolidadoLibro;
        }
        public IActionResult VistaMain_Cliente()
        {
            ViewBag.Reciente = _iconsolidado.GetAllCatalogoRecientemente();
            ViewBag.Infantil = _iconsolidado.GetAllCatalogoInfantil();
            ViewBag.Cuento = _iconsolidado.GetAllCatalogoCuento();
            ViewBag.Novela = _iconsolidado.GetAllCatalogoNovela();
            ViewBag.Poesia = _iconsolidado.GetAllCatalogoPoesia();
            ViewBag.Terror = _iconsolidado.GetAllCatalogoTerror();
            ViewBag.Accion = _iconsolidado.GetAllCatalogoAccion();
            ViewBag.Aventura = _iconsolidado.GetAllCatalogoAventura();
            ViewBag.Romance = _iconsolidado.GetAllCatalogoRomance();


            var objsession = HttpContext.Session.GetString("sUsuario");
            if (objsession != null)
            {
                var obj = JsonConvert.DeserializeObject<Usuario> (HttpContext.Session.GetString("sUsuario"));
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Usuario");
            }
        }
        public IActionResult VistaMain_Admin()
        {
            ViewBag.CountLibros = _ilibro.GetAllLibros().Count();
            ViewBag.CountAutores = _iautor.GetAllAutores().Count();
            ViewBag.CountEditoriales = _ieditorial.GetAllEditoriales().Count();

            var objsession = HttpContext.Session.GetString("sUsuario");
            if (objsession != null)
            {
                var obj = JsonConvert.DeserializeObject<Usuario>(HttpContext.Session.GetString("sUsuario"));
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Usuario");
            }
            
        }
    }
}

WEB/Views/VistaMain/VistaMain_Admin.cshtml
@{
    /*Layout = "~/Views/Shared/Layouts/Layout_Admin.cshtml"*/;
}
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    int countLibros = ViewBag.CountLibros;
    int countAutores = ViewBag.CountAutores;
    int countEditoriales = ViewBag.CountEditoriales;
}

<!DOCTYPE html>
<html lang="es">
<head>
    <title>Inicio</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="Shortcut Icon" type="image/x-icon" href="assets/img/book.png" />
    <script src="js/sweet-alert.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="~/css/diseño_bootstrap.css">
    <link rel="stylesheet" href="~/css/diseño_admin.css">
</head>
<body>
    <div class="navbar-lateral full-reset">
        <div class="visible-xs font-movile-menu mobile-menu-button"></div>
        <div class="full-reset container-menu-movile custom-scroll-containers">
            <div class="logo full-reset all-tittles">
                <i class="visible-xs zmdi zmdi-close pull-left mobile-menu-button" style="line-height: 55px; cursor: pointer; padding: 0 10px; margin-left: 7px;"></i> 
                biblioteca
            </div>
            <div class="full-reset" style="background-color:#2B3D51; padding: 10px 0; color:#fff;">
                <figure>
                    <img src="~/assets/img/libro.png" alt="Biblioteca" class="img-responsive center-box" style="width:55%;">
                </figure>
                <p class="text-center" style="padding-top: 15px;">Biblioteca</p>
            </div>
            <div class="full-reset nav-lateral-list-menu">
                <ul class="list-unstyled">
                    <li><a asp-controller="VistaMain" asp-action="VistaMain_Admin"><i class="zmdi zmdi-home zmdi-hc-fw"></i>&nbsp;&nbsp; Inicio</a></li>
                    <li>
                        <div class="dropdown-menu-button" onclick="toggleDropdown(this)"><i class="zmdi zmdi-assignment-o zmdi-hc-fw"></i>&nbsp;&nbsp; Libros <i class="material-icons pull-right">swap_vert</i></div>
                        <ul class="list-unstyled">
                            <li><a asp-controller="Registro_Libro_Editorial" asp-action="ListadoCatalogo"><i class="zmdi zmdi-bookmark-outline zmdi-hc-fw"></i>&nbsp;&nbsp; Lista de libros</a></li>
                            <li><a asp-controller="Registro_Libro_Editorial" asp-action="FormularioRegistro"><i class="zmdi zmdi-book zmdi-hc-fw"></i>&nbsp;&nbsp; Nuevo libro</a></li>
                            <li><a asp-controller="Registro_Libro_Editorial" asp-action="FormularioEditRegistro"><i class="zmdi zmdi-book zmdi-hc-fw"></i>&nbsp;&nbsp; Editar y eliminar libro</a></li>
                        </ul>
                    </li>
                    <li>
                        <div class="dropdown-menu-button" onclick="toggleDropdown(this)"><i class="zmdi zmdi-account-add zmdi-hc-fw"></i>&nbsp;&nbsp; Autores <i class="material-icons pull-right">swap_vert</i></div>
                        <ul class="list-unstyled">
                            <li><a asp-controller="Autor" asp-action="ListadoAutor"><i class="zmdi zmdi-face zmdi-hc-fw"></i>&nbsp;&nbsp; Lista Autores</a></li>
                            <li><a asp-controller="Autor" asp-action="FormularioAutor"><i class="zmdi zmdi-face zmdi-hc-fw"></i>&nbsp;&nbsp; Nuevo autor</a></li>
                            <li><a asp-controller="Autor" asp-action="FormularioEditAutor"><i class="zmdi zmdi-male-alt zmdi-hc-fw"></i>&nbsp;&nbsp; Editar y eliminar autor</a></li>
                        </ul>
                    </li>
                    <li>
                        <div class="dropdown-menu-button" onclick="toggleDropdown(this)" ><i class="zmdi zmdi-account-add zmdi-hc-fw"></i>&nbsp;&nbsp; Editoriales <i class="material-icons pull-right">swap_vert</i></div>
                        <ul class="list-unstyled">
                            <li><a asp-controller="Editorial" asp-action="ListadoEditorial"><i class="zmdi zmdi-face zmdi-hc-fw"></i>&nbsp;&nbsp; Lista editoriales</a></li>
                            <li><a asp-controller="Editorial" asp-action="FormularioEditorial"><i class="zmdi zmdi-face zmdi-hc-fw"></i>&nbsp;&nbsp; Nuevo editorial</a></li>
                            <li><a asp-controller="Editorial" asp-action="FormularioEditEditorial"><i class="zmdi zmdi-male-alt zmdi-hc-fw"></i>&nbsp;&nbsp; Editar y eliminar editorial</a></li>
                        </ul>
                    </li>
                    <li>
                        <div class="dropdown-menu-button" onclick="toggleDropdown(this)" ><i class="zmdi zmdi-alarm zmdi-hc-fw"></i>&nbsp;&nbsp; Reservaciones y devoluciones <i class="material-icons pull-right">swap_vert</i></div>
                        <ul class="list-unstyled">
                            <li><a href="loan.html"><i class="zmdi zmdi-calendar zmdi-hc-fw"></i>&nbsp;&nbsp; Todos las reservaciones</a></li>
                            <li>
                                <a href="loanpending.html"><i class="zmdi zmdi-time-restore zmdi-hc-fw"></i>&nbsp;&nbsp; Devoluciones pendientes <span class="label label-danger pull-right label-mhover">7</span></a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <script>
                function toggleDropdown(button) {
                  var dropdown = button.nextElementSibling;
                  dropdown.style.display = dropdown.style.display === 'none' ? 'block' : 'none';
                }
              </script>
        </div>
    </div>
    <div class="content-page-container full-reset custom-scroll-containers">
        <nav class="navbar-user-top full-reset">
            <ul class="list-unstyled full-reset">
                <figure>
                   <img src="~/assets/img/user01.png" alt="user-picture" class="img-responsive img-circle center-box">
                </figure>
                <li style="color:#fff; cursor:default;">
                    <span class="all-tittles">Admin</span>
                </li>
                <li  class="tooltips-general exit-system-button" data-href="index.html" data-placement="bottom" title="Salir del sistema">
                    <a asp-controller="Usuario" asp-action="CerrarSesion"><i class="material-icons">logout</i></a>
                </li>
                <li  class="tooltips-general search-book-button" data-href="searchbook.html" data-placement="bottom" title="Buscar libro">
                    <i class="zmdi zmdi-search"></i>
                </li>
                <li  class="tooltips-general btn-help" data-placement="bottom" title="Ayuda">
                    <i class="zmdi zmdi-help-outline zmdi-hc-fw"></i>
                </li>
                <li class="mobile-menu-button visible-xs" style="float: left !important;">
                    <i class="zmdi zmdi-menu"></i>
                </li>
            </ul>
        </nav>
        <div class="container">
            <div class="page-header">
              <h1 class="all-tittles">Listados</h1>
            </div>
        </div>
        <section class="full-reset text-center" style="padding: 40px 0;">
            @{/*<a asp-controller="Autor" asp-action="ListadoAutor">
            <article class="tile">
                <div class="tile-icon full-reset"><i class="zmdi zmdi-face"></i></div>
                <div class="tile-name all-tittles">administradores</div>
                <div class="tile-num full-reset">7</div>
            </article>
            </a>
            <article class="tile">
                <div class="tile-icon full-reset"><i class="zmdi zmdi-accounts"></i></div>
                <div class="tile-name all-tittles">clientes</div>
                <div class="tile-num full-reset">70</div>
            </article>*/}
            <a asp-controller="Registro_Libro_Editorial" asp-action="ListadoCatalogo">
                <article class="tile">
                <div class="tile-icon full-reset"><i class="material-icons" style="font-size: 45px;">book</i></div>
                <div class="tile-name all-tittles">libros</div>
                <div class="tile-num full-reset">@countLibros</div>
            </article>
            </a>
            <a asp-controller="Autor" asp-action="ListadoAutor">
                <article class="tile">
                <div class="tile-icon full-reset"><i class="material-icons" style="font-size: 45px;">face</i></div>
                <div class="tile-name all-tittles">autores</div>
                <div class="tile-num full-reset">@countAutores</div>
            </article>
            </a>
            <a asp-controller="Editorial" asp-action="ListadoEditorial">
                <article class="tile">
                <div class="tile-icon full-reset"><i class="material-icons" style="font-size: 45px;">add_business</i></div>
                <div class="tile-name all-tittles">editoriales</div>
                <div class="tile-num full-reset">@countEditoriales</div>
            </article>
            </a>
            @{/*<article class="tile">
                <div class="tile-icon full-reset"><i class="zmdi zmdi-bookmark-outline"></i></div>
                <div class="tile-name all-tittles">categorías</div>
                <div class="tile-num full-reset">11</div>
            </article>
            <article class="tile">
                <div class="tile-icon full-reset"><i class="zmdi zmdi-timer"></i></div>
                <div class="tile-name all-tittles">reservaciones</div>
                <div class="tile-num full-reset">10</div>
            </article>
            <article class="tile">
                <div class="tile-icon full-reset"><i class="zmdi zmdi-time-restore"></i></div>
                <div class="tile-name all-tittles" style="width: 90%;">devoluciones pendientes</div>
                <div class="tile-num full-reset">9</div>
            </article>*/}
        </section>
    </div>
</body>
</html>