WEB/Models/Editorial.cs
using System;
using System.Collections.Generic;

namespace BIBLIOTECA_VIRTUAL.Models;

public partial class Editorial
{
    public int IdEditorial { get; set; }

    public string RazonSocial { get; set; } = null!;

    public string Ruc { get; set; } = null!;

    public string Direccion { get; set; } = null!;

    public string CorreoElec { get; set; } = null!;

    public bool Estado { get; set; }

    public virtual ICollection<Libro> Libros { get; set; } = new List<Libro>();
}

WEB/Controllers/EditorialController.cs
using BIBLIOTECA_VIRTUAL.Models;
using BIBLIOTECA_VIRTUAL.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace BIBLIOTECA_VIRTUAL.Controllers
{
    public class EditorialController : Controller
    {
        private readonly IEditorial _ieditorial;

        public EditorialController(IEditorial editorial)
        {
            _ieditorial = editorial;
        }

        public IActionResult ListadoEditorial()
        {
            return View(_ieditorial.GetAllEditoriales());
        }
        public IActionResult FormularioEditorial()
        {
            return View();
        }
        public IActionResult AñadirEditorial(Editorial objEditorial)
        {
            _ieditorial.AñadiEditorial(objEditorial);
            TempData["Mensaje"] = "Se añadio correctamente la editorial!!!";
            return RedirectToAction("FormularioEditorial");
        }
        public IActionResult FormularioEditEditorial()
        {
            return View(_ieditorial.GetAllEditorialesTrue());
        }

        [Route("Editorial/FormularioModificar/{IdEditorial}")]
        public IActionResult FormularioModificar(int IdEditorial)
        {
            var objAutor = _ieditorial.GetIdEditorialModificar(IdEditorial);

            return View(objAutor);
        }

        public IActionResult ModificarEditorial(Editorial objEditorial)
        {
            _ieditorial.EditDetails_Editorial(objEditorial);
            TempData["Mensaje"] = "Se modifico correctamente!!";
            return RedirectToAction("FormularioEditEditorial");
        }

        [Route("Editorial/EliminarEditorial/{IdEditorial}")]
        public IActionResult EliminarEditorial(int IdEditorial)
        {
            bool flag = _ieditorial.EliminarEditorial(IdEditorial);
            if (flag == true)
            {
                TempData["Mensaje"] = "Se elimino correctamente!!";
                return RedirectToAction("FormularioEditEditorial");
            }
            else
            {
                TempData["Mensaje"] = "Hubo un error al momento de elimnar";
                return RedirectToAction("FormularioEditEditorial");
            }
        }
    }
}

WEB/Views/Editorial/FormularioEditEditorial.cshtml
@{
    Layout = "~/Views/Shared/Layouts/Layout_Editorial.cshtml";
}
@model IEnumerable<BIBLIOTECA_VIRTUAL.Models.Editorial>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
        <LINK REL=StyleSheet HREF="~/css/TablaLibros.css" TYPE="text/css" MEDIA=screen>
    <style>
        .table-bordered tr, .table-bordered td {
            border: 2px solid #000;
        }

        .table-bordered tr,
        .table-bordered td {
            border: 2px solid #000;
        }


        .table-bordered td,
        .table-bordered th {
            border: 2px solid #000;
            position: relative;
        }

            .table-bordered td::before,
            .table-bordered th::before {
                content: "";
                position: absolute;
                left: -2px;
                top: 0;
                bottom: 0;
                width: 2px;
                background-color: #000;
            }
    </style>
    </head>
    <body>
    <h1><strong>PANEL EDITAR Y ELIMINAR EDITORIAL</strong></h1>
        <table class="table table-bordered">
            <tr>
            <td><strong>Codigo</strong></td>
            <td><strong>Razon social</strong></td>
            <td><strong>Ruc</strong></td>
            <td><strong>Direccion</strong></td>
            <td><strong>Correo electronico</strong></td>
            <td><strong>Accion editar</strong></td>
            <td><strong>Accion eliminar</strong></td>
            </tr>
            <tbody>
                @foreach(var item in Model)
                {
                    <tr>
                        <td>@item.IdEditorial</td>
                        <td>@item.RazonSocial</td>
                        <td>@item.Ruc</td>
                        <td>@item.Direccion</td>
                        <td>@item.CorreoElec</td>
                        <td>
                            <div class="form-group">
                                <a asp-controller="Editorial" asp-action="FormularioModificar" asp-route-id="@item.IdEditorial" type="submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Editar</a>
                            </div>
                        </td>
                        <td>
                            <div class="form-group">
                                <a asp-controller="Editorial" asp-action="EliminarEditorial" asp-route-id="@item.IdEditorial" type="submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Eliminar</a>
                            </div>
                        </td>
                    </tr>
                }
        </tbody>
        </table>
        @if (TempData["Mensaje"] != null)
            {
                <script>
                    window.onload = function() {
                        alert("@TempData["Mensaje"]");
                    };
                </script>
            }
    </body>
</html>

WEB/Views/Editorial/FormularioEditorial.cshtml
@{
    Layout = "~/Views/Shared/Layouts/Layout_Editorial.cshtml";
}
@model BIBLIOTECA_VIRTUAL.Models.Editorial
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
        <LINK REL=StyleSheet HREF="~/css/FormularioAutor.css" TYPE="text/css" MEDIA=screen>
    </head>
    <body class ="RegisterCliAd">
        <div class="container">
          <h1>REGISTRO</h1>
            <form asp-controller="Editorial" asp-action="AñadirEditorial" method="post">
                <div class="form-group">
                    <label for="formGroupExampleInput">Razon social</label>
                    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Razon social" asp-for="RazonSocial">
                    <span asp-validation-for="RazonSocial" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label for="formGroupExampleInput2">Ruc</label>
                    <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Ruc" asp-for="Ruc">
                    <span asp-validation-for="Ruc" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label for="formGroupExampleInput2">Direccion</label>
                    <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Direccion" asp-for="Direccion">
                    <span asp-validation-for="Direccion" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label for="formGroupExampleInput2">Correo electronioc</label>
                    <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Correo electronico" asp-for="CorreoElec">
                    <span asp-validation-for="CorreoElec" class="text-danger"></span>
                </div>
                <div class="form-group">
                <input type="hidden" asp-for="Estado" value="true" />
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary" value="btn" name="Agregar" data-toggle="modal" data-target="#exampleModal">Agregar</button>
                </div>
                <div class="form-group">
                </div>
            </form>
            @if (TempData["Mensaje"] != null)
            {
                <script>
                    window.onload = function() {
                        alert("@TempData["Mensaje"]");
                    };
                </script>
            }
        </div>
    </body>
</html>

WEB/Views/Editorial/FormularioModificar.cshtml
@{
    Layout = "~/Views/Shared/Layouts/Layout_Editorial.cshtml";
}
@model BIBLIOTECA_VIRTUAL.Models.Editorial
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
        <LINK REL=StyleSheet HREF="~/css/style.css" TYPE="text/css" MEDIA=screen>
    </head>
    <body class ="RegisterCliAd">
        <div class="container">
          <h1>EDITAR EDITORIAL</h1>
            <form asp-controller="Editorial" asp-action="ModificarEditorial" method="post">
                <div class="form-group">
                <input type="hidden" asp-for="IdEditorial" value="@Model.IdEditorial" />
                </div>
                <div class="form-group">
                    <label for="formGroupExampleInput">Razon social</label>
                    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Razon social" asp-for="RazonSocial" value="@Model.RazonSocial">
                    <span asp-validation-for="RazonSocial" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label for="formGroupExampleInput">Ruc</label>
                    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Ruc" asp-for="Ruc" value="@Model.Ruc">
                    <span asp-validation-for="Ruc" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label for="formGroupExampleInput">Direccion</label>
                    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Direccion" asp-for="Direccion" value="@Model.Direccion">
                    <span asp-validation-for="Direccion" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label for="formGroupExampleInput2">Correo electronico</label>
                    <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Correo electronico" asp-for="CorreoElec" value="@Model.CorreoElec">
                    <span asp-validation-for="CorreoElec" class="text-danger"></span>
                </div>
                <div class="form-group">
                <input type="hidden" asp-for="Estado" value="true" />
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary" value="btn" name="Editar" data-toggle="modal" data-target="#exampleModal">Editar</button>
                </div>
                <div class="form-group">
                </div>
            </form>
        </div>
    </body>
</html>

WEB/Views/Editorial/ListadoEditorial.cshtml
@{
    Layout = "~/Views/Shared/Layouts/Layout_Editorial.cshtml";
}
@model IEnumerable<BIBLIOTECA_VIRTUAL.Models.Editorial>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
    <head>
        <link rel="stylesheet" href="~/css/ListadoEditorial.css" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/jquery.slick/1.6.0/slick.css">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://cdn.jsdelivr.net/jquery.slick/1.6.0/slick.min.js"></script>
    </head>
    <body>
        <h2><strong>LISTA DE EDITORES</strong></h2>
        <div class="card-deck">
            @foreach(var item in Model)
            {
              <div class="card m-4" style="min-width:18rem;max-width:30.5%;">
                <div class="card-header">
                    <h3>@item.RazonSocial</h3>
                    <h5>@item.Ruc</h5>
                    <h5>@item.Direccion</h5>
                    <h5>@item.CorreoElec</h5>
                    @if(@item.Estado){
                        <h6>Activo</h6>
                    }else{
                        <h6>Inactivo</h6>
                    }
                </div>
              </div>
            }
        </div>
    <script>
        $(document).ready(function () {
            $('.card-carousel').slick({
                slidesToShow: 3, // Define cuántas tarjetas se muestran al mismo tiempo
                slidesToScroll: 1, // Define cuántas tarjetas se desplazan al hacer clic en los controles
                autoplay: true, // Activa el carrusel automático
                autoplaySpeed: 2000 // Define la velocidad de reproducción automática en milisegundos
            });
        });
    </script>
    </body>
</html>