WEB/Models/DetalleLibro.cs
using System;
using System.Collections.Generic;

namespace BIBLIOTECA_VIRTUAL.Models;

public partial class DetalleLibro
{
    public int IdLibro { get; set; }

    public string Sinopsis { get; set; } = null!;

    public virtual Libro IdLibroNavigation { get; set; } = null!;
}

WEB/Controllers/ConsolidadoController.cs
using BIBLIOTECA_VIRTUAL.Models;
using BIBLIOTECA_VIRTUAL.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace BIBLIOTECA_VIRTUAL.Controllers
{
    public class ConsolidadoController : Controller
    {
        private readonly IConsolidadoLibro _iconsolidado;
        private readonly ICategoria _icategoria;
        private readonly IAutor _iautor;

        public ConsolidadoController(IConsolidadoLibro consolidadoLibro, ICategoria categoria, IAutor autor)
        {
            _iconsolidado = consolidadoLibro;
            _icategoria = categoria;
            _iautor = autor;
        }
        [Route("Consolidado/DetalleLibro/{IdLibro}")]
        public IActionResult DetalleLibro(int IdLibro)
        {
            var objEncrontrado = _iconsolidado.GetIdLibro(IdLibro);
            return View(objEncrontrado);
        }

        public IActionResult Catalogo(IEnumerable<ConsolidadoLibro>? autores, IEnumerable<ConsolidadoLibro>? categorias, IEnumerable<ConsolidadoLibro>? cateAutor)
        {
            ViewBag.Categorias1 = _icategoria.GetAllCategorias();
            ViewBag.Autores = _iautor.GetAllAutoresTrue();
            if(autores.Count() == 0 && categorias.Count() == 0 && cateAutor.Count() == 0)
            {
                return View(_iconsolidado.GetAllCatalogoView());
            }
            else if(autores.Count() > 0 && categorias.Count() == 0 && cateAutor.Count() == 0)
            {
                return View(autores);
            }
            else if(categorias.Count() > 0 && autores.Count() == 0 && cateAutor.Count() == 0)
            {
                return View(categorias);
            }
            else
            {
                return View(cateAutor);
            }
            
        }
        public IActionResult Buscar(string titulo, string categoria, string autores)
        {

            if (titulo != null && categoria != null && autores != null)
            {
                int idLibro = _iconsolidado.GetTituCateAutoIdLibro(titulo, categoria, autores);
                if (idLibro != -1)
                {
                    return RedirectToAction("DetalleLibro", new { id = idLibro });
                }
                else
                {
                    return RedirectToAction("LibroNoFound");
                }
            }
            else if (categoria != null && autores != null)
            {
                if (_iconsolidado.GetCateAutorIdLibro(categoria, autores).Count() > 0)
                {
                    return RedirectToAction("Catalogo", new { cateAutor = _iconsolidado.GetCateAutorIdLibro(categoria, autores) });
                }
                else
                {
                    return RedirectToAction("LibroNoFound");
                }
            }
            else if(titulo != null && autores == null && categoria == null)
            {
                int idLibro = _iconsolidado.GetTituloIdLibro(titulo);
                if (idLibro != -1)
                {
                    return RedirectToAction("DetalleLibro", new { id = idLibro });
                }
                else
                {
                    return RedirectToAction("LibroNoFound");
                }
            }
            else if(autores != null && categoria == null && titulo == null)
            {
                if (_iconsolidado.GetAutorLibro(autores).Count() > 0)
                {
                    return RedirectToAction("Catalogo", new { autores = _iconsolidado.GetAutorLibro(autores)});
                }
                else
                {
                    return RedirectToAction("LibroNoFound");
                }
            }
            else if(categoria != null && titulo == null && autores == null)
            {
                if (_iconsolidado.GetCategoriaIdLibro(categoria).Count() > 0)
                {
                    return RedirectToAction("Catalogo", new { categorias = _iconsolidado.GetCategoriaIdLibro(categoria)});
                }
                else
                {
                    return RedirectToAction("LibroNoFound");
                }
            }
            else
            {
                return RedirectToAction("LibroNoFound");
            }
        }
        public IActionResult LibroNoFound()
        {
            ViewBag.Categorias1 = _icategoria.GetAllCategorias();
            ViewBag.Autores = _iautor.GetAllAutoresTrue();
            return View();
        }
    }
}

WEB/Views/Consolidado/Catalogo.cshtml
@{
    Layout = "~/Views/Shared/Layouts/Layout_Cliente.cshtml";
}
@model IEnumerable<BIBLIOTECA_VIRTUAL.Models.ConsolidadoLibro>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    IEnumerable<Categorium> Categoria = ViewBag.Categorias1;
    IEnumerable<Autor> Autores = ViewBag.Autores;
}
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/ListadoLibros.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/jquery.slick/1.6.0/slick.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.slick/1.6.0/slick.min.js"></script>
</head>
<body>
    <h1>LISTA DE CATALOGO</h1>
    <form asp-controller="Consolidado" asp-action="Buscar" method="post">
        <input type="text" name="titulo" class="form-text" placeholder="BuscarLibro" />
        <select class="form-control" id="categoria" name="categoria">
            <option value="">Categorias</option>
            @foreach (var item in Categoria)
                {
                     <option value="@item.Descripcion">@item.Descripcion</option>
                }
        </select>
        <select class="form-control" id="autores" name="autores">
            <option value="">Autores</option>
            @foreach (var item in Autores)
                {
                     <option value="@item.NombreApellido">@item.NombreApellido</option>
                }
        </select>
        <div class="form-group">
        <input type="submit" placeholder="Buscar" class="btn btn-dark" />
        </div>
    </form>
    
    <div class="card-deck">
        <div class="card-carousel">
            @foreach (var item in Model)
            {
                <div class="card" style="min-width:18rem;max-width:10.5%;">
                    <div class="card-header">
                        @{
                            string rutaImagenRelativa = @item.RutaImagen;
                            rutaImagenRelativa = rutaImagenRelativa.Replace("\\", "/").Replace("\\", "/");
                        }
                        <img src="@Url.Content(rutaImagenRelativa)" alt="Imagen del catálogo" style="width: 100%; height: auto;">
                        <h4>@item.Titulo</h4>
                        <h5>@item.Categoria</h5>
                        <h6>@item.Autor</h6>
                        <h6>@item.FechaPublicacion.ToShortDateString()</h6>
                        <div class="form-group">
                                <a asp-controller="Consolidado" asp-action="DetalleLibro" asp-route-id="@item.IdLibro" type="submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Revisar</a>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</body>
</html>

WEB/Views/Consolidado/DetalleLibro.cshtml
@{
    Layout = "~/Views/Shared/Layouts/Layout_Cliente.cshtml";
}
@model BIBLIOTECA_VIRTUAL.Models.ConsolidadoLibro
@{
    string rutaImagenRelativa = @Model.RutaImagen;
    rutaImagenRelativa = rutaImagenRelativa.Replace("~\\", "~/").Replace("\\", "/");
}
<html>
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.4.0/dist/css/bootstrap.min.css">
    </head>
    <body>
        <div class="container" style="margin-top: 20px;">
            <div class="card">
                <div class="row">
                    <div class="col-md-4">
                        <img src="@Url.Content(rutaImagenRelativa)" alt="Imagen del catálogo" class="img-fluid">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h1 class="card-title">@Model.Titulo</h1>
                            <h5 class="card-subtitle mb-2 text-muted">@Model.Autor</h5>
                            <p class="card-text">@Model.Sinopsis</p>
                            <p class="card-text">Fecha de publicación: @Model.FechaPublicacion.ToShortDateString()</p>
                            <div class="card-text">
                                <span class="badge bg-primary">@Model.Categoria</span>
                            </div>
                        </div>
                     <form asp-controller="TemporalPrestamo" asp-action="AgregarCarrito" method="post">
                        <input type="hidden" name="codLibro" value="@Model.IdLibro" />
                        <input type="hidden" name="txtTitulo" value="@Model.Titulo" />
                        <input type="hidden" name="txtAutor" value="@Model.Autor" />
                        <input type="hidden" name="txtEditorial" value="@Model.Editorial" />
                        <input type="hidden" name="txtCategoria" value="@Model.Categoria" />
                        <input type="submit"  class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" value="Reservar" />
                    </form>
                    </div>
                </div>
            </div>
        </div>
        
    </body>
</html>

WEB/Views/Consolidado/LibroNoFound.cshtml
@{
    Layout = "~/Views/Shared/Layouts/Layout_Cliente.cshtml";
}
@model IEnumerable<BIBLIOTECA_VIRTUAL.Models.ConsolidadoLibro>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    IEnumerable<Categorium> Categoria = ViewBag.Categorias1;
    IEnumerable<Autor> Autores = ViewBag.Autores;
}
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/ListadoLibros.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/jquery.slick/1.6.0/slick.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.slick/1.6.0/slick.min.js"></script>
</head>
<body>
    <h1>LISTA DE CATALOGO</h1>
    <form asp-controller="Consolidado" asp-action="Buscar" method="post">
        <input type="text" name="titulo" class="form-text" placeholder="BuscarLibro" />
        <select class="form-control" id="categoria" name="categoria">
            <option value="">Categorias</option>
            @foreach (var item in Categoria)
                {
                     <option value="@item.Descripcion">@item.Descripcion</option>
                }
        </select>
        <select class="form-control" id="autores" name="autores">
            <option value="">Autores</option>
            @foreach (var item in Autores)
                {
                     <option value="@item.NombreApellido">@item.NombreApellido</option>
                }
        </select>
        <div class="form-group">
        <input type="submit" placeholder="Buscar" class="btn btn-dark" />
        </div>
    </form>
    <h1 class="text text-danger">NO HAY LIBROS ENCONTRADOS</h1>
</body>
</html>